version: '4'
services:
  mongoDB:
    image: mongo:7.0.5
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INIT_DB_ROOT_USERNAME: root
      MONGO_INIT_DB_ROOT_PASSWORD: password
      MONGO_INIT_DB_DATABASE: product-service
    volumes:
      - ./data:/data/db

